# Generated by Django 4.2.13 on 2024-05-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mail',
            new_name='email',
        ),
    ]
