# Generated by Django 4.2.13 on 2024-05-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_3', '0002_rename_mail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='name',
            field=models.ForeignKey(default='placeholder', on_delete=django.db.models.deletion.CASCADE, to='app_3.first_name'),
            preserve_default=False,
        ),
    ]
