# Generated by Django 4.2.13 on 2024-06-04 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 7, 40, 28, 62122, tzinfo=datetime.timezone.utc)),
        ),
    ]
