# Generated by Django 4.2.13 on 2024-06-08 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_rename_create_date_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 6, 8, 13, 12, 58, 999147, tzinfo=datetime.timezone.utc), upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
