# Generated by Django 4.2.13 on 2024-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='uploads/', width_field='image_width'),
        ),
    ]
