# Generated by Django 4.2.13 on 2024-06-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_post_image_height_post_width_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='uploads/', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='width_field',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
