# Generated by Django 4.2.13 on 2024-06-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_post_image_alter_post_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog_app.comment')),
            ],
        ),
    ]
